# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        args: [--safe, --line-length=100, --preview]
    -   id: black-jupyter
        args: [--safe, --line-length=100, --preview]
        language_version: python3.9

-   repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter

ci:
    autoupdate_schedule: weekly
